### ISSUE TITLE
luarocks does not work on windows when trying to install luacurl

### ISSUE THREAD

**Issue by rayaman** [Lua-cURL/Lua-cURLv3#100]
C:\Windows\System32>luarocks install Lua-cURL --server=https://luarocks.org/dev
C:\Program Files (x86)\Lua\5.1\lua: C:\Program Files (x86)\Lua\5.1\lua/luarocks\fs.lua:37: attempt to concatenate local
'loaded_platform' (a nil value)
stack traceback:
        C:\Program Files (x86)\Lua\5.1\lua/luarocks\fs.lua:37: in main chunk
        [C]: in function 'require'
        ...rogram Files (x86)\Lua\5.1\lua\luarocks\command_line.lua:7: in main chunk
        [C]: in function 'require'
        C:\Program Files (x86)\Lua\5.1\luarocks.lua:3: in main chunk
        [C]: at 0x004020f0

What do you think the problem might be?

**Comment by rayaman** [comment]
Fixed it by changing the command to: luarocks install lua-curl --server=https://luarocks.org/dev
the upper case Lua-cURL was causing the error

**Comment by moteus** [comment]
This is known `feature` of LuaRocks. You have to use lower case in command. Even if module has upper case in its name. Not sure is it documented thoug.
Just curious. Did your LuaRocks uses wget to get archive or you install LuaSec.
When I try install I [fail](https://github.com/luarocks/luarocks/issues/713) because of wget can not download archive.
Also why you need dev version. In fact in dev I have only one bug fix reletad with HTTP2

**Comment by rayaman** [comment]
Luarocks didnt use wget i was able to get luasec to work. It worked after i made it lowercase and i updated to the latest version of luarocks.

 I like using the latest even if it ts dev stuff
